### PR TITLE
Create strings.xml for Italian language

### PR DESCRIPTION
**Pull request by airon90**
Add Italian localization. Ping me here if new translations are available

### CODE REVIEW

**Comment by brarcher** [comment]
Thanks for contributing Italian translations, and thanks for the interest.

The build failed for the following reason:

```
:app:processDebugResources/home/travis/build/brarcher/gift-card-guard/app/build/intermediates/res/merged/debug/values-it/values-it.xml:32 : AAPT: Apostrophe not preceded by \ (in Al momento non hai alcuna tessera regalo. Premi sul bottone "+" (più) in alto per iniziare.\n\nTessere regalo ti permette di gestire le tessere regalo e il loro attuale valore. Un'immagine opzionale della tessera ti permetterà di gestire i problemi con i commercianti se vengono trovate anomalie.)
```

Would you mind updating the commit and trying again?

**Comment by airon90** [comment]
Oops, I'm so sorry! I fixed my error :) Now it should work all correctly!

**Comment by brarcher** [comment]
Could you squish the two commits together into one? Then, I'll merge them into the project.

Thanks!

**Comment by airon90** [comment]
Ehm, sincerely I don't know how to do that ^^' 
Please could you tell me how to do that via GitHub (or via git command)?
Thank you :)

**Comment by brarcher** [comment]
Ah, did not realize you were only using the github interface. No worries.

After I added the setting for currency, there are a few more strings that need translating. Interested in translating them as well, and resubmitting?

**Comment by airon90** [comment]
Updated. 
Please ping me here if new keys are available ;)

**Comment by brarcher** [comment]
Is there an option to update the branch to master? Github does not want to merge the request as it because the branch is out of date.

If there is no such button, maybe just copy the translations into another pull request and resubmit.

**Comment by airon90** [comment]
Done. Or I belive I did it :D

**Comment by brarcher** [comment]
Hey @airon90,

To help with making translations easier, I've opened a project on Transifex for this app. If you would like to help keep translations up-to-date in the future, please take a look on [Transifex](https://www.transifex.com/na-243/gift-card-guard). If you lose the link, it is also in the README.

Thanks!

**Pull request merged**
